version: '3.7'

volumes:
  goaccess_report: { driver: local }

services:

  goaccess_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: eduardoreno/goaccess_server
    restart: unless-stopped
    container_name: goaccess_server
    ports:
      - 7890:7890
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./server/goaccess.conf:/srv/data/goaccess.conf:ro
      - goaccess_report:/srv/report
    # Target log
      - ${TARGET_LOG}:ro

  goaccess_web:
    image: nginx
    restart: unless-stopped
    container_name: goaccess_web
    ports:
      - 7891:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/.htpasswd:/etc/nginx/.htpasswd:ro
      - goaccess_report:/srv/report:ro
    depends_on:
      - goaccess_server